### ISSUE TITLE
Exception in thread "main" java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by AliYns** [manoelcampos/cloudsim-plus#172]
I'm trying to run MigrationExample1, but I get error below.
do I have to change something before running this example?

Starting MigrationExample1

Starting CloudSim Plus 4.1.2
INFO  DatacenterSimple1 is starting...
INFO  DatacenterBrokerSimple2 is starting...
INFO  Entities started.
INFO  0.0: DatacenterBrokerSimple2: List of 1 datacenters(s) received.
INFO  0.0: DatacenterBrokerSimple2: Trying to Create Vm 0/Broker 2 in DatacenterSimple1
INFO  0.0: DatacenterBrokerSimple2: Trying to Create Vm 1/Broker 2 in DatacenterSimple1
INFO  0.0: DatacenterBrokerSimple2: Trying to Create Vm 2/Broker 2 in DatacenterSimple1
INFO  0.0: VmAllocationPolicyMigrationBestFitStaticThreshold: Vm 0/Broker 2 has been allocated to Host 0/DC 1
INFO  0.0: VmAllocationPolicyMigrationBestFitStaticThreshold: Vm 1/Broker 2 has been allocated to Host 1/DC 1
INFO  0.0: VmAllocationPolicyMigrationBestFitStaticThreshold: Vm 2/Broker 2 has been allocated to Host 1/DC 1
INFO  0.1: DatacenterBrokerSimple2: Sending Cloudlet 0 to Vm 0/Broker 2 in Host 0/DC 1.
INFO  0.1: DatacenterBrokerSimple2: Sending Cloudlet 1 to Vm 1/Broker 2 in Host 1/DC 1.
INFO  0.1: DatacenterBrokerSimple2: Sending Cloudlet 2 to Vm 2/Broker 2 in Host 1/DC 1.
INFO  0.1: DatacenterBrokerSimple2: All waiting Cloudlets submitted to some VM.
Exception in thread "main" java.util.ConcurrentModificationException
	at java.util.ArrayList.forEach(ArrayList.java:1252)
	at org.cloudbus.cloudsim.brokers.DatacenterBrokerAbstract.notifyOnVmsCreatedListeners(DatacenterBrokerAbstract.java:637)
	at org.cloudbus.cloudsim.brokers.DatacenterBrokerAbstract.processVmCreateResponseFromDatacenter(DatacenterBrokerAbstract.java:628)
	at org.cloudbus.cloudsim.brokers.DatacenterBrokerAbstract.processVmEvents(DatacenterBrokerAbstract.java:464)
	at org.cloudbus.cloudsim.brokers.DatacenterBrokerAbstract.processEvent(DatacenterBrokerAbstract.java:422)
	at org.cloudbus.cloudsim.core.CloudSimEntity.run(CloudSimEntity.java:336)
	at org.cloudbus.cloudsim.core.CloudSim.executeRunnableEntities(CloudSim.java:500)
	at org.cloudbus.cloudsim.core.CloudSim.runClockTickAndProcessFutureEvents(CloudSim.java:428)
	at org.cloudbus.cloudsim.core.CloudSim.eventLoop(CloudSim.java:263)
	at org.cloudbus.cloudsim.core.CloudSim.start(CloudSim.java:229)
	at org.cloudsimplus.examples.migration.MigrationExample1.<init>(MigrationExample1.java:211)
	at org.cloudsimplus.examples.migration.MigrationExample1.main(MigrationExample1.java:192)

Process finished with exit code 1

**Comment by manoelcampos** [comment]
I've just fixed the issue.
Thanks for reporting.
